packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
  "@tailwindcss/oxide": true

onlyBuiltDependencies:
  - "esbuild"
  - "workerd"
  - "sharp"
  - "@tailwindcss/oxide"
